version: '3'

services:
  php-apache:
    build:
      context: ./docker/php-apache
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/php-apache:/usr/local/apache2/logs/
    ports:
      - "8080:80"
    networks:
      net:
        ipv4_address: '10.100.0.21'
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: 'common'
      MYSQL_USER: 'common'
      MYSQL_PASSWORD: '486464'
      MYSQL_ROOT_PASSWORD: '486464'
    ports:
      - "33061:3306"
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24