version: '1'

services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: bitrix-${PROJECT_NAME}-mysql
    container_name: bitrix-${PROJECT_NAME}-mysql
    restart: "always"
    volumes:
      - ./settings/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "33061:3306"
    networks:
      - net

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    image: bitrix-${PROJECT_NAME}-php-apache
    container_name: bitrix-${PROJECT_NAME}-php-apache
    restart: "always"
    # depends_on: 
    #   - mysql
    volumes:
      - type: bind
        source: ./settings/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
      - type: bind
        source: ./settings/php.ini
        target: /usr/local/etc/php/conf.d/php.ini
      - type: bind
        source: ./docker/logs/php-apache
        target: /usr/local/apache2/logs
      - type: bind
        source: ./www/local
        target: /var/www/html/local
    ports:
      - "80:80"
    networks:
      - net

  memcached:
    build:
      context: ./docker/memcached
      dockerfile: Dockerfile
    image: bitrix-${PROJECT_NAME}-memcached
    container_name: bitrix-${PROJECT_NAME}-memcached
    restart: "always"
    volumes:
      - ./docker/storage/memcached:/var/lib/memcached
    ports:
      - "11211"
    depends_on:
      - php-apache
    networks:
      - net

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    image: bitrix-${PROJECT_NAME}-redis
    container_name: bitrix-${PROJECT_NAME}-redis
    restart: "always"
    volumes:
      - ./docker/storage/redis:/data
    networks:
      - net

networks:
  net: