version: '1'

services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: 'common'
      MYSQL_USER: 'common'
      MYSQL_PASSWORD: '486464'
      MYSQL_ROOT_PASSWORD: '486464'
    ports:
      - "33061:3306"
    networks:
      - net

  php-apache:
    build:
      context: ./docker/php-apache
      dockerfile: Dockerfile
    working_dir: /var/www/html
    depends_on: 
      - mysql
    volumes:
      - ./www/local/templates:/var/www/html/local/templates
      - ./docker/logs/php-apache:/usr/local/apache2/logs/
    ports:
      - "8080:80"
    networks:
      - net

  memcached:
    build:
      context: ./docker/memcached
      dockerfile: Dockerfile
    volumes:
      - ./docker/storage/memcached:/var/lib/memcached
    ports:
      - "11211"
    depends_on:
      - php-apache
    networks:
      - net

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    volumes:
      - ./docker/storage/redis:/data
    # ports:
    #   - "6379"
    networks:
      - net

networks:
  net: